// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, description, config, status, user_id) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, name, description, config, status, user_id, created_at, updated_at
`

type CreateAgentParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Status      pgtype.Text `json:"status"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Status,
		arg.UserID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents 
WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, name, description, config, status, user_id, created_at, updated_at 
FROM agents 
WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentsByUserID = `-- name: GetAgentsByUserID :many
SELECT id, name, description, config, status, user_id, created_at, updated_at 
FROM agents 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetAgentsByUserID(ctx context.Context, userID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, getAgentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Status,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents 
SET name = $2, description = $3, config = $4, status = $5, updated_at = NOW() 
WHERE id = $1 
RETURNING id, name, description, config, status, user_id, created_at, updated_at
`

type UpdateAgentParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.Status,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
