// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: app_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppConnection = `-- name: CreateAppConnection :one
INSERT INTO app_connections (project_id, name, app_name, config, credentials, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, app_name, config, credentials, status, created_at, updated_at
`

type CreateAppConnectionParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Name        string      `json:"name"`
	AppName     string      `json:"app_name"`
	Config      []byte      `json:"config"`
	Credentials []byte      `json:"credentials"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) CreateAppConnection(ctx context.Context, arg CreateAppConnectionParams) (AppConnection, error) {
	row := q.db.QueryRow(ctx, createAppConnection,
		arg.ProjectID,
		arg.Name,
		arg.AppName,
		arg.Config,
		arg.Credentials,
		arg.Status,
	)
	var i AppConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AppName,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppConnection = `-- name: DeleteAppConnection :exec
DELETE FROM app_connections
WHERE id = $1
`

func (q *Queries) DeleteAppConnection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppConnection, id)
	return err
}

const getAppConnectionByID = `-- name: GetAppConnectionByID :one
SELECT id, project_id, name, app_name, config, credentials, status, created_at, updated_at
FROM app_connections
WHERE id = $1
`

func (q *Queries) GetAppConnectionByID(ctx context.Context, id pgtype.UUID) (AppConnection, error) {
	row := q.db.QueryRow(ctx, getAppConnectionByID, id)
	var i AppConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AppName,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppConnectionByName = `-- name: GetAppConnectionByName :one
SELECT id, project_id, name, app_name, config, credentials, status, created_at, updated_at
FROM app_connections
WHERE project_id = $1 AND name = $2
`

type GetAppConnectionByNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) GetAppConnectionByName(ctx context.Context, arg GetAppConnectionByNameParams) (AppConnection, error) {
	row := q.db.QueryRow(ctx, getAppConnectionByName, arg.ProjectID, arg.Name)
	var i AppConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AppName,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppConnectionsByAppName = `-- name: GetAppConnectionsByAppName :many
SELECT id, project_id, name, app_name, config, credentials, status, created_at, updated_at
FROM app_connections
WHERE project_id = $1 AND app_name = $2
ORDER BY created_at DESC
`

type GetAppConnectionsByAppNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	AppName   string      `json:"app_name"`
}

func (q *Queries) GetAppConnectionsByAppName(ctx context.Context, arg GetAppConnectionsByAppNameParams) ([]AppConnection, error) {
	rows, err := q.db.Query(ctx, getAppConnectionsByAppName, arg.ProjectID, arg.AppName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppConnection{}
	for rows.Next() {
		var i AppConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.AppName,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppConnectionsByProjectID = `-- name: GetAppConnectionsByProjectID :many

SELECT id, project_id, name, app_name, config, credentials, status, created_at, updated_at
FROM app_connections
WHERE project_id = $1
ORDER BY created_at DESC
`

// App Connections queries (external service integrations)
func (q *Queries) GetAppConnectionsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]AppConnection, error) {
	rows, err := q.db.Query(ctx, getAppConnectionsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppConnection{}
	for rows.Next() {
		var i AppConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.AppName,
			&i.Config,
			&i.Credentials,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppConnection = `-- name: UpdateAppConnection :one
UPDATE app_connections
SET name = $2, app_name = $3, config = $4, credentials = $5, status = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, app_name, config, credentials, status, created_at, updated_at
`

type UpdateAppConnectionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	AppName     string      `json:"app_name"`
	Config      []byte      `json:"config"`
	Credentials []byte      `json:"credentials"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdateAppConnection(ctx context.Context, arg UpdateAppConnectionParams) (AppConnection, error) {
	row := q.db.QueryRow(ctx, updateAppConnection,
		arg.ID,
		arg.Name,
		arg.AppName,
		arg.Config,
		arg.Credentials,
		arg.Status,
	)
	var i AppConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.AppName,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppConnectionStatus = `-- name: UpdateAppConnectionStatus :exec
UPDATE app_connections
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAppConnectionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateAppConnectionStatus(ctx context.Context, arg UpdateAppConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppConnectionStatus, arg.ID, arg.Status)
	return err
}
