// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: executions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (workflow_id, agent_id, status, input_data, started_at) 
VALUES ($1, $2, $3, $4, $5) 
RETURNING id, workflow_id, agent_id, status, input_data, output_data, error_message, 
          execution_time_ms, started_at, completed_at, created_at
`

type CreateExecutionParams struct {
	WorkflowID pgtype.UUID        `json:"workflow_id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Status     pgtype.Text        `json:"status"`
	InputData  []byte             `json:"input_data"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.WorkflowID,
		arg.AgentID,
		arg.Status,
		arg.InputData,
		arg.StartedAt,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.ErrorMessage,
		&i.ExecutionTimeMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, workflow_id, agent_id, status, input_data, output_data, error_message, 
       execution_time_ms, started_at, completed_at, created_at 
FROM executions 
WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id pgtype.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.ErrorMessage,
		&i.ExecutionTimeMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionsByAgentID = `-- name: GetExecutionsByAgentID :many
SELECT id, workflow_id, agent_id, status, input_data, output_data, error_message, 
       execution_time_ms, started_at, completed_at, created_at 
FROM executions 
WHERE agent_id = $1 
ORDER BY started_at DESC 
LIMIT $2
`

type GetExecutionsByAgentIDParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) GetExecutionsByAgentID(ctx context.Context, arg GetExecutionsByAgentIDParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, getExecutionsByAgentID, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.ErrorMessage,
			&i.ExecutionTimeMs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionsByUserID = `-- name: GetExecutionsByUserID :many
SELECT e.id, e.workflow_id, e.agent_id, e.status, e.input_data, e.output_data, 
       e.error_message, e.execution_time_ms, e.started_at, e.completed_at, e.created_at 
FROM executions e 
JOIN workflows w ON e.workflow_id = w.id 
WHERE w.user_id = $1 
ORDER BY e.started_at DESC 
LIMIT $2
`

type GetExecutionsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetExecutionsByUserID(ctx context.Context, arg GetExecutionsByUserIDParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, getExecutionsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.ErrorMessage,
			&i.ExecutionTimeMs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionsByWorkflowID = `-- name: GetExecutionsByWorkflowID :many
SELECT id, workflow_id, agent_id, status, input_data, output_data, error_message, 
       execution_time_ms, started_at, completed_at, created_at 
FROM executions 
WHERE workflow_id = $1 
ORDER BY started_at DESC 
LIMIT $2
`

type GetExecutionsByWorkflowIDParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) GetExecutionsByWorkflowID(ctx context.Context, arg GetExecutionsByWorkflowIDParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, getExecutionsByWorkflowID, arg.WorkflowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Status,
			&i.InputData,
			&i.OutputData,
			&i.ErrorMessage,
			&i.ExecutionTimeMs,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDByWorkflowID = `-- name: GetUserIDByWorkflowID :one
SELECT user_id FROM workflows WHERE id = $1
`

func (q *Queries) GetUserIDByWorkflowID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserIDByWorkflowID, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE executions 
SET status = $2, output_data = $3, completed_at = $4, execution_time_ms = $5, error_message = $6 
WHERE id = $1 
RETURNING id, workflow_id, agent_id, status, input_data, output_data, error_message, 
          execution_time_ms, started_at, completed_at, created_at
`

type UpdateExecutionStatusParams struct {
	ID              pgtype.UUID        `json:"id"`
	Status          pgtype.Text        `json:"status"`
	OutputData      []byte             `json:"output_data"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ExecutionTimeMs pgtype.Int4        `json:"execution_time_ms"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatus,
		arg.ID,
		arg.Status,
		arg.OutputData,
		arg.CompletedAt,
		arg.ExecutionTimeMs,
		arg.ErrorMessage,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Status,
		&i.InputData,
		&i.OutputData,
		&i.ErrorMessage,
		&i.ExecutionTimeMs,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
