// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: flow_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlowVersion = `-- name: CreateFlowVersion :one
INSERT INTO flow_versions (flow_id, version, display_name, trigger, steps, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
`

type CreateFlowVersionParams struct {
	FlowID      pgtype.UUID `json:"flow_id"`
	Version     int32       `json:"version"`
	DisplayName string      `json:"display_name"`
	Trigger     []byte      `json:"trigger"`
	Steps       []byte      `json:"steps"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) CreateFlowVersion(ctx context.Context, arg CreateFlowVersionParams) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, createFlowVersion,
		arg.FlowID,
		arg.Version,
		arg.DisplayName,
		arg.Trigger,
		arg.Steps,
		arg.Status,
	)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowVersion = `-- name: DeleteFlowVersion :exec
DELETE FROM flow_versions
WHERE id = $1
`

func (q *Queries) DeleteFlowVersion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowVersion, id)
	return err
}

const getFlowVersionByID = `-- name: GetFlowVersionByID :one
SELECT id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
FROM flow_versions
WHERE id = $1
`

func (q *Queries) GetFlowVersionByID(ctx context.Context, id pgtype.UUID) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, getFlowVersionByID, id)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowVersionByVersion = `-- name: GetFlowVersionByVersion :one
SELECT id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
FROM flow_versions
WHERE flow_id = $1 AND version = $2
`

type GetFlowVersionByVersionParams struct {
	FlowID  pgtype.UUID `json:"flow_id"`
	Version int32       `json:"version"`
}

func (q *Queries) GetFlowVersionByVersion(ctx context.Context, arg GetFlowVersionByVersionParams) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, getFlowVersionByVersion, arg.FlowID, arg.Version)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowVersionsByFlowID = `-- name: GetFlowVersionsByFlowID :many

SELECT id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
FROM flow_versions
WHERE flow_id = $1
ORDER BY version DESC
`

// Flow Versions queries (versioned flow definitions)
func (q *Queries) GetFlowVersionsByFlowID(ctx context.Context, flowID pgtype.UUID) ([]FlowVersion, error) {
	rows, err := q.db.Query(ctx, getFlowVersionsByFlowID, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowVersion{}
	for rows.Next() {
		var i FlowVersion
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Version,
			&i.DisplayName,
			&i.Trigger,
			&i.Steps,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowVersionsWithRuns = `-- name: GetFlowVersionsWithRuns :many
SELECT 
    fv.id, fv.flow_id, fv.version, fv.display_name, fv.trigger, fv.steps, fv.status, fv.created_at, fv.updated_at,
    COUNT(fr.id) as run_count,
    COUNT(CASE WHEN fr.status = 'SUCCEEDED' THEN 1 END) as success_count,
    COUNT(CASE WHEN fr.status = 'FAILED' THEN 1 END) as failure_count
FROM flow_versions fv
LEFT JOIN flow_runs fr ON fv.id = fr.flow_version_id
WHERE fv.flow_id = $1
GROUP BY fv.id, fv.flow_id, fv.version, fv.display_name, fv.trigger, fv.steps, fv.status, fv.created_at, fv.updated_at
ORDER BY fv.version DESC
`

type GetFlowVersionsWithRunsRow struct {
	ID           pgtype.UUID        `json:"id"`
	FlowID       pgtype.UUID        `json:"flow_id"`
	Version      int32              `json:"version"`
	DisplayName  string             `json:"display_name"`
	Trigger      []byte             `json:"trigger"`
	Steps        []byte             `json:"steps"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	RunCount     int64              `json:"run_count"`
	SuccessCount int64              `json:"success_count"`
	FailureCount int64              `json:"failure_count"`
}

func (q *Queries) GetFlowVersionsWithRuns(ctx context.Context, flowID pgtype.UUID) ([]GetFlowVersionsWithRunsRow, error) {
	rows, err := q.db.Query(ctx, getFlowVersionsWithRuns, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowVersionsWithRunsRow{}
	for rows.Next() {
		var i GetFlowVersionsWithRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Version,
			&i.DisplayName,
			&i.Trigger,
			&i.Steps,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RunCount,
			&i.SuccessCount,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestFlowVersion = `-- name: GetLatestFlowVersion :one
SELECT id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
FROM flow_versions
WHERE flow_id = $1
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLatestFlowVersion(ctx context.Context, flowID pgtype.UUID) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, getLatestFlowVersion, flowID)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextVersionNumber = `-- name: GetNextVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1 as next_version
FROM flow_versions
WHERE flow_id = $1
`

func (q *Queries) GetNextVersionNumber(ctx context.Context, flowID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextVersionNumber, flowID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const getPublishedFlowVersion = `-- name: GetPublishedFlowVersion :one
SELECT id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
FROM flow_versions
WHERE flow_id = $1 AND status = 'PUBLISHED'
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetPublishedFlowVersion(ctx context.Context, flowID pgtype.UUID) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, getPublishedFlowVersion, flowID)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishFlowVersion = `-- name: PublishFlowVersion :exec
UPDATE flow_versions
SET status = CASE WHEN id = $2 THEN 'PUBLISHED' ELSE 'LOCKED' END,
    updated_at = NOW()
WHERE flow_id = $1 AND status IN ('PUBLISHED', 'DRAFT')
`

type PublishFlowVersionParams struct {
	FlowID pgtype.UUID `json:"flow_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) PublishFlowVersion(ctx context.Context, arg PublishFlowVersionParams) error {
	_, err := q.db.Exec(ctx, publishFlowVersion, arg.FlowID, arg.ID)
	return err
}

const updateFlowVersion = `-- name: UpdateFlowVersion :one
UPDATE flow_versions
SET display_name = $2, trigger = $3, steps = $4, status = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, flow_id, version, display_name, trigger, steps, status, created_at, updated_at
`

type UpdateFlowVersionParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName string      `json:"display_name"`
	Trigger     []byte      `json:"trigger"`
	Steps       []byte      `json:"steps"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdateFlowVersion(ctx context.Context, arg UpdateFlowVersionParams) (FlowVersion, error) {
	row := q.db.QueryRow(ctx, updateFlowVersion,
		arg.ID,
		arg.DisplayName,
		arg.Trigger,
		arg.Steps,
		arg.Status,
	)
	var i FlowVersion
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Version,
		&i.DisplayName,
		&i.Trigger,
		&i.Steps,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowVersionStatus = `-- name: UpdateFlowVersionStatus :exec
UPDATE flow_versions
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFlowVersionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateFlowVersionStatus(ctx context.Context, arg UpdateFlowVersionStatusParams) error {
	_, err := q.db.Exec(ctx, updateFlowVersionStatus, arg.ID, arg.Status)
	return err
}
