// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: flows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (project_id, folder_id, status, schedule)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, folder_id, status, schedule, created_at, updated_at
`

type CreateFlowParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	FolderID  pgtype.UUID `json:"folder_id"`
	Status    pgtype.Text `json:"status"`
	Schedule  []byte      `json:"schedule"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.ProjectID,
		arg.FolderID,
		arg.Status,
		arg.Schedule,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Status,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows
WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlow, id)
	return err
}

const getEnabledFlows = `-- name: GetEnabledFlows :many
SELECT id, project_id, folder_id, status, schedule, created_at, updated_at
FROM flows
WHERE status = 'ENABLED'
ORDER BY created_at
`

func (q *Queries) GetEnabledFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, getEnabledFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flow{}
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Status,
			&i.Schedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowByID = `-- name: GetFlowByID :one
SELECT f.id, f.project_id, f.folder_id, f.status, f.schedule, f.created_at, f.updated_at,
       fo.display_name as folder_name
FROM flows f
LEFT JOIN folders fo ON f.folder_id = fo.id
WHERE f.id = $1
`

type GetFlowByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	FolderID   pgtype.UUID        `json:"folder_id"`
	Status     pgtype.Text        `json:"status"`
	Schedule   []byte             `json:"schedule"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FolderName pgtype.Text        `json:"folder_name"`
}

func (q *Queries) GetFlowByID(ctx context.Context, id pgtype.UUID) (GetFlowByIDRow, error) {
	row := q.db.QueryRow(ctx, getFlowByID, id)
	var i GetFlowByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Status,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FolderName,
	)
	return i, err
}

const getFlowsByProjectID = `-- name: GetFlowsByProjectID :many

SELECT f.id, f.project_id, f.folder_id, f.status, f.schedule, f.created_at, f.updated_at,
       fo.display_name as folder_name
FROM flows f
LEFT JOIN folders fo ON f.folder_id = fo.id
WHERE f.project_id = $1
ORDER BY f.created_at DESC
`

type GetFlowsByProjectIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	FolderID   pgtype.UUID        `json:"folder_id"`
	Status     pgtype.Text        `json:"status"`
	Schedule   []byte             `json:"schedule"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FolderName pgtype.Text        `json:"folder_name"`
}

// Flows queries (flow definitions)
func (q *Queries) GetFlowsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]GetFlowsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getFlowsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowsByProjectIDRow{}
	for rows.Next() {
		var i GetFlowsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Status,
			&i.Schedule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FolderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledFlows = `-- name: GetScheduledFlows :many
SELECT id, project_id, folder_id, status, schedule, created_at, updated_at
FROM flows
WHERE status = 'ENABLED' AND schedule IS NOT NULL
ORDER BY created_at
`

func (q *Queries) GetScheduledFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, getScheduledFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Flow{}
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Status,
			&i.Schedule,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :one
UPDATE flows
SET folder_id = $2, status = $3, schedule = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, folder_id, status, schedule, created_at, updated_at
`

type UpdateFlowParams struct {
	ID       pgtype.UUID `json:"id"`
	FolderID pgtype.UUID `json:"folder_id"`
	Status   pgtype.Text `json:"status"`
	Schedule []byte      `json:"schedule"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, updateFlow,
		arg.ID,
		arg.FolderID,
		arg.Status,
		arg.Schedule,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Status,
		&i.Schedule,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowStatus = `-- name: UpdateFlowStatus :exec
UPDATE flows
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFlowStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateFlowStatus(ctx context.Context, arg UpdateFlowStatusParams) error {
	_, err := q.db.Exec(ctx, updateFlowStatus, arg.ID, arg.Status)
	return err
}
