// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: flow_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlowRun = `-- name: CreateFlowRun :one
INSERT INTO flow_runs (flow_version_id, project_id, status, environment, flow_display_name, tags, pause_metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, flow_version_id, project_id, status, start_time, finish_time, environment, flow_display_name, logs_file_id, tags, pause_metadata, created_at, updated_at
`

type CreateFlowRunParams struct {
	FlowVersionID   pgtype.UUID `json:"flow_version_id"`
	ProjectID       pgtype.UUID `json:"project_id"`
	Status          pgtype.Text `json:"status"`
	Environment     pgtype.Text `json:"environment"`
	FlowDisplayName pgtype.Text `json:"flow_display_name"`
	Tags            []string    `json:"tags"`
	PauseMetadata   []byte      `json:"pause_metadata"`
}

func (q *Queries) CreateFlowRun(ctx context.Context, arg CreateFlowRunParams) (FlowRun, error) {
	row := q.db.QueryRow(ctx, createFlowRun,
		arg.FlowVersionID,
		arg.ProjectID,
		arg.Status,
		arg.Environment,
		arg.FlowDisplayName,
		arg.Tags,
		arg.PauseMetadata,
	)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowVersionID,
		&i.ProjectID,
		&i.Status,
		&i.StartTime,
		&i.FinishTime,
		&i.Environment,
		&i.FlowDisplayName,
		&i.LogsFileID,
		&i.Tags,
		&i.PauseMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowRun = `-- name: DeleteFlowRun :exec
DELETE FROM flow_runs
WHERE id = $1
`

func (q *Queries) DeleteFlowRun(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFlowRun, id)
	return err
}

const getFlowRunByID = `-- name: GetFlowRunByID :one
SELECT fr.id, fr.flow_version_id, fr.project_id, fr.status, fr.start_time, fr.finish_time, 
       fr.environment, fr.flow_display_name, fr.logs_file_id, fr.tags, fr.pause_metadata, fr.created_at, fr.updated_at,
       fv.display_name as flow_version_name, fv.version as flow_version_number, fv.steps, fv.trigger
FROM flow_runs fr
LEFT JOIN flow_versions fv ON fr.flow_version_id = fv.id
WHERE fr.id = $1
`

type GetFlowRunByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	FlowVersionID     pgtype.UUID        `json:"flow_version_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Status            pgtype.Text        `json:"status"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	FinishTime        pgtype.Timestamptz `json:"finish_time"`
	Environment       pgtype.Text        `json:"environment"`
	FlowDisplayName   pgtype.Text        `json:"flow_display_name"`
	LogsFileID        pgtype.UUID        `json:"logs_file_id"`
	Tags              []string           `json:"tags"`
	PauseMetadata     []byte             `json:"pause_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FlowVersionName   pgtype.Text        `json:"flow_version_name"`
	FlowVersionNumber pgtype.Int4        `json:"flow_version_number"`
	Steps             []byte             `json:"steps"`
	Trigger           []byte             `json:"trigger"`
}

func (q *Queries) GetFlowRunByID(ctx context.Context, id pgtype.UUID) (GetFlowRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getFlowRunByID, id)
	var i GetFlowRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.FlowVersionID,
		&i.ProjectID,
		&i.Status,
		&i.StartTime,
		&i.FinishTime,
		&i.Environment,
		&i.FlowDisplayName,
		&i.LogsFileID,
		&i.Tags,
		&i.PauseMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FlowVersionName,
		&i.FlowVersionNumber,
		&i.Steps,
		&i.Trigger,
	)
	return i, err
}

const getFlowRunStats = `-- name: GetFlowRunStats :one
SELECT 
    fr.project_id,
    COUNT(*) as total_runs,
    COUNT(CASE WHEN fr.status = 'SUCCEEDED' THEN 1 END) as success_count,
    COUNT(CASE WHEN fr.status = 'FAILED' THEN 1 END) as failure_count,
    COUNT(CASE WHEN fr.status = 'RUNNING' THEN 1 END) as running_count,
    COUNT(CASE WHEN fr.status = 'PAUSED' THEN 1 END) as paused_count,
    AVG(EXTRACT(EPOCH FROM (fr.finish_time - fr.start_time))) as avg_duration_seconds
FROM flow_runs fr
WHERE fr.project_id = $1 
  AND fr.start_time >= $2
GROUP BY fr.project_id
`

type GetFlowRunStatsParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

type GetFlowRunStatsRow struct {
	ProjectID          pgtype.UUID `json:"project_id"`
	TotalRuns          int64       `json:"total_runs"`
	SuccessCount       int64       `json:"success_count"`
	FailureCount       int64       `json:"failure_count"`
	RunningCount       int64       `json:"running_count"`
	PausedCount        int64       `json:"paused_count"`
	AvgDurationSeconds float64     `json:"avg_duration_seconds"`
}

func (q *Queries) GetFlowRunStats(ctx context.Context, arg GetFlowRunStatsParams) (GetFlowRunStatsRow, error) {
	row := q.db.QueryRow(ctx, getFlowRunStats, arg.ProjectID, arg.StartTime)
	var i GetFlowRunStatsRow
	err := row.Scan(
		&i.ProjectID,
		&i.TotalRuns,
		&i.SuccessCount,
		&i.FailureCount,
		&i.RunningCount,
		&i.PausedCount,
		&i.AvgDurationSeconds,
	)
	return i, err
}

const getFlowRunsByFlowID = `-- name: GetFlowRunsByFlowID :many
SELECT fr.id, fr.flow_version_id, fr.project_id, fr.status, fr.start_time, fr.finish_time, 
       fr.environment, fr.flow_display_name, fr.logs_file_id, fr.tags, fr.pause_metadata, fr.created_at, fr.updated_at,
       fv.display_name as flow_version_name, fv.version as flow_version_number
FROM flow_runs fr
LEFT JOIN flow_versions fv ON fr.flow_version_id = fv.id
LEFT JOIN flows f ON fv.flow_id = f.id
WHERE f.id = $1
ORDER BY fr.start_time DESC
LIMIT $2 OFFSET $3
`

type GetFlowRunsByFlowIDParams struct {
	ID     pgtype.UUID `json:"id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetFlowRunsByFlowIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	FlowVersionID     pgtype.UUID        `json:"flow_version_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Status            pgtype.Text        `json:"status"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	FinishTime        pgtype.Timestamptz `json:"finish_time"`
	Environment       pgtype.Text        `json:"environment"`
	FlowDisplayName   pgtype.Text        `json:"flow_display_name"`
	LogsFileID        pgtype.UUID        `json:"logs_file_id"`
	Tags              []string           `json:"tags"`
	PauseMetadata     []byte             `json:"pause_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FlowVersionName   pgtype.Text        `json:"flow_version_name"`
	FlowVersionNumber pgtype.Int4        `json:"flow_version_number"`
}

func (q *Queries) GetFlowRunsByFlowID(ctx context.Context, arg GetFlowRunsByFlowIDParams) ([]GetFlowRunsByFlowIDRow, error) {
	rows, err := q.db.Query(ctx, getFlowRunsByFlowID, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowRunsByFlowIDRow{}
	for rows.Next() {
		var i GetFlowRunsByFlowIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowVersionID,
			&i.ProjectID,
			&i.Status,
			&i.StartTime,
			&i.FinishTime,
			&i.Environment,
			&i.FlowDisplayName,
			&i.LogsFileID,
			&i.Tags,
			&i.PauseMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlowVersionName,
			&i.FlowVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowRunsByProjectID = `-- name: GetFlowRunsByProjectID :many

SELECT fr.id, fr.flow_version_id, fr.project_id, fr.status, fr.start_time, fr.finish_time, 
       fr.environment, fr.flow_display_name, fr.logs_file_id, fr.tags, fr.pause_metadata, fr.created_at, fr.updated_at,
       fv.display_name as flow_version_name, fv.version as flow_version_number
FROM flow_runs fr
LEFT JOIN flow_versions fv ON fr.flow_version_id = fv.id
WHERE fr.project_id = $1
ORDER BY fr.start_time DESC
LIMIT $2 OFFSET $3
`

type GetFlowRunsByProjectIDParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type GetFlowRunsByProjectIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	FlowVersionID     pgtype.UUID        `json:"flow_version_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Status            pgtype.Text        `json:"status"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	FinishTime        pgtype.Timestamptz `json:"finish_time"`
	Environment       pgtype.Text        `json:"environment"`
	FlowDisplayName   pgtype.Text        `json:"flow_display_name"`
	LogsFileID        pgtype.UUID        `json:"logs_file_id"`
	Tags              []string           `json:"tags"`
	PauseMetadata     []byte             `json:"pause_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FlowVersionName   pgtype.Text        `json:"flow_version_name"`
	FlowVersionNumber pgtype.Int4        `json:"flow_version_number"`
}

// Flow Runs queries (execution instances)
func (q *Queries) GetFlowRunsByProjectID(ctx context.Context, arg GetFlowRunsByProjectIDParams) ([]GetFlowRunsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, getFlowRunsByProjectID, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowRunsByProjectIDRow{}
	for rows.Next() {
		var i GetFlowRunsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowVersionID,
			&i.ProjectID,
			&i.Status,
			&i.StartTime,
			&i.FinishTime,
			&i.Environment,
			&i.FlowDisplayName,
			&i.LogsFileID,
			&i.Tags,
			&i.PauseMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlowVersionName,
			&i.FlowVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowRunsByStatus = `-- name: GetFlowRunsByStatus :many
SELECT fr.id, fr.flow_version_id, fr.project_id, fr.status, fr.start_time, fr.finish_time, 
       fr.environment, fr.flow_display_name, fr.logs_file_id, fr.tags, fr.pause_metadata, fr.created_at, fr.updated_at
FROM flow_runs fr
WHERE fr.project_id = $1 AND fr.status = ANY($2::text[])
ORDER BY fr.start_time DESC
LIMIT $3 OFFSET $4
`

type GetFlowRunsByStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Column2   []string    `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) GetFlowRunsByStatus(ctx context.Context, arg GetFlowRunsByStatusParams) ([]FlowRun, error) {
	rows, err := q.db.Query(ctx, getFlowRunsByStatus,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlowRun{}
	for rows.Next() {
		var i FlowRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowVersionID,
			&i.ProjectID,
			&i.Status,
			&i.StartTime,
			&i.FinishTime,
			&i.Environment,
			&i.FlowDisplayName,
			&i.LogsFileID,
			&i.Tags,
			&i.PauseMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowRunsWithFilters = `-- name: GetFlowRunsWithFilters :many
SELECT fr.id, fr.flow_version_id, fr.project_id, fr.status, fr.start_time, fr.finish_time, 
       fr.environment, fr.flow_display_name, fr.logs_file_id, fr.tags, fr.pause_metadata, fr.created_at, fr.updated_at,
       fv.display_name as flow_version_name, fv.version as flow_version_number
FROM flow_runs fr
LEFT JOIN flow_versions fv ON fr.flow_version_id = fv.id
LEFT JOIN flows f ON fv.flow_id = f.id
WHERE fr.project_id = $1
  AND ($2::uuid[] IS NULL OR f.id = ANY($2::uuid[]))
  AND ($3::text[] IS NULL OR fr.status = ANY($3::text[]))
  AND ($4::text[] IS NULL OR fr.tags && $4::text[])
  AND ($5::timestamp IS NULL OR fr.start_time >= $5)
  AND ($6::timestamp IS NULL OR fr.start_time <= $6)
ORDER BY fr.start_time DESC
LIMIT $7 OFFSET $8
`

type GetFlowRunsWithFiltersParams struct {
	ProjectID pgtype.UUID      `json:"project_id"`
	Column2   []pgtype.UUID    `json:"column_2"`
	Column3   []string         `json:"column_3"`
	Column4   []string         `json:"column_4"`
	Column5   pgtype.Timestamp `json:"column_5"`
	Column6   pgtype.Timestamp `json:"column_6"`
	Limit     int32            `json:"limit"`
	Offset    int32            `json:"offset"`
}

type GetFlowRunsWithFiltersRow struct {
	ID                pgtype.UUID        `json:"id"`
	FlowVersionID     pgtype.UUID        `json:"flow_version_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Status            pgtype.Text        `json:"status"`
	StartTime         pgtype.Timestamptz `json:"start_time"`
	FinishTime        pgtype.Timestamptz `json:"finish_time"`
	Environment       pgtype.Text        `json:"environment"`
	FlowDisplayName   pgtype.Text        `json:"flow_display_name"`
	LogsFileID        pgtype.UUID        `json:"logs_file_id"`
	Tags              []string           `json:"tags"`
	PauseMetadata     []byte             `json:"pause_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	FlowVersionName   pgtype.Text        `json:"flow_version_name"`
	FlowVersionNumber pgtype.Int4        `json:"flow_version_number"`
}

func (q *Queries) GetFlowRunsWithFilters(ctx context.Context, arg GetFlowRunsWithFiltersParams) ([]GetFlowRunsWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, getFlowRunsWithFilters,
		arg.ProjectID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFlowRunsWithFiltersRow{}
	for rows.Next() {
		var i GetFlowRunsWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowVersionID,
			&i.ProjectID,
			&i.Status,
			&i.StartTime,
			&i.FinishTime,
			&i.Environment,
			&i.FlowDisplayName,
			&i.LogsFileID,
			&i.Tags,
			&i.PauseMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlowVersionName,
			&i.FlowVersionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningFlowRuns = `-- name: GetRunningFlowRuns :many
SELECT id, flow_version_id, project_id, status, start_time, flow_display_name, pause_metadata
FROM flow_runs
WHERE status IN ('RUNNING', 'PAUSED')
ORDER BY start_time
`

type GetRunningFlowRunsRow struct {
	ID              pgtype.UUID        `json:"id"`
	FlowVersionID   pgtype.UUID        `json:"flow_version_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Status          pgtype.Text        `json:"status"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	FlowDisplayName pgtype.Text        `json:"flow_display_name"`
	PauseMetadata   []byte             `json:"pause_metadata"`
}

func (q *Queries) GetRunningFlowRuns(ctx context.Context) ([]GetRunningFlowRunsRow, error) {
	rows, err := q.db.Query(ctx, getRunningFlowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRunningFlowRunsRow{}
	for rows.Next() {
		var i GetRunningFlowRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowVersionID,
			&i.ProjectID,
			&i.Status,
			&i.StartTime,
			&i.FlowDisplayName,
			&i.PauseMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryFlowRun = `-- name: RetryFlowRun :one
INSERT INTO flow_runs (flow_version_id, project_id, status, environment, flow_display_name, tags, pause_metadata)
SELECT flow_version_id, project_id, 'RUNNING', environment, flow_display_name, tags, '{}'::jsonb
FROM flow_runs
WHERE flow_runs.id = $1
RETURNING id, flow_version_id, project_id, status, start_time, finish_time, environment, flow_display_name, logs_file_id, tags, pause_metadata, created_at, updated_at
`

func (q *Queries) RetryFlowRun(ctx context.Context, id pgtype.UUID) (FlowRun, error) {
	row := q.db.QueryRow(ctx, retryFlowRun, id)
	var i FlowRun
	err := row.Scan(
		&i.ID,
		&i.FlowVersionID,
		&i.ProjectID,
		&i.Status,
		&i.StartTime,
		&i.FinishTime,
		&i.Environment,
		&i.FlowDisplayName,
		&i.LogsFileID,
		&i.Tags,
		&i.PauseMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFlowRunPauseMetadata = `-- name: UpdateFlowRunPauseMetadata :exec
UPDATE flow_runs
SET pause_metadata = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFlowRunPauseMetadataParams struct {
	ID            pgtype.UUID `json:"id"`
	PauseMetadata []byte      `json:"pause_metadata"`
}

func (q *Queries) UpdateFlowRunPauseMetadata(ctx context.Context, arg UpdateFlowRunPauseMetadataParams) error {
	_, err := q.db.Exec(ctx, updateFlowRunPauseMetadata, arg.ID, arg.PauseMetadata)
	return err
}

const updateFlowRunStatus = `-- name: UpdateFlowRunStatus :exec
UPDATE flow_runs
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateFlowRunStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateFlowRunStatus(ctx context.Context, arg UpdateFlowRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateFlowRunStatus, arg.ID, arg.Status)
	return err
}

const updateFlowRunStatusWithFinishTime = `-- name: UpdateFlowRunStatusWithFinishTime :exec
UPDATE flow_runs
SET status = $2, finish_time = NOW(), updated_at = NOW()
WHERE id = $1
`

type UpdateFlowRunStatusWithFinishTimeParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateFlowRunStatusWithFinishTime(ctx context.Context, arg UpdateFlowRunStatusWithFinishTimeParams) error {
	_, err := q.db.Exec(ctx, updateFlowRunStatusWithFinishTime, arg.ID, arg.Status)
	return err
}
