// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (name, type, config, credentials, user_id, is_active) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, name, type, config, user_id, is_active, created_at, updated_at
`

type CreateIntegrationParams struct {
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Config      []byte      `json:"config"`
	Credentials []byte      `json:"credentials"`
	UserID      string      `json:"user_id"`
	IsActive    pgtype.Bool `json:"is_active"`
}

type CreateIntegrationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	UserID    string             `json:"user_id"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (CreateIntegrationRow, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Credentials,
		arg.UserID,
		arg.IsActive,
	)
	var i CreateIntegrationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations 
WHERE id = $1 AND user_id != 'system'
`

func (q *Queries) DeleteIntegration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteIntegration, id)
	return err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, name, type, config, credentials, user_id, is_active, created_at, updated_at 
FROM integrations 
WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id pgtype.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Credentials,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationsByUserID = `-- name: GetIntegrationsByUserID :many
SELECT id, name, type, config, user_id, is_active, created_at, updated_at 
FROM integrations 
WHERE user_id = $1 OR user_id = 'system' 
ORDER BY created_at DESC
`

type GetIntegrationsByUserIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	UserID    string             `json:"user_id"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetIntegrationsByUserID(ctx context.Context, userID string) ([]GetIntegrationsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getIntegrationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetIntegrationsByUserIDRow{}
	for rows.Next() {
		var i GetIntegrationsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations 
SET name = $2, type = $3, config = $4, credentials = $5, is_active = $6, updated_at = NOW() 
WHERE id = $1 
RETURNING id, name, type, config, user_id, is_active, created_at, updated_at
`

type UpdateIntegrationParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Config      []byte      `json:"config"`
	Credentials []byte      `json:"credentials"`
	IsActive    pgtype.Bool `json:"is_active"`
}

type UpdateIntegrationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	UserID    string             `json:"user_id"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (UpdateIntegrationRow, error) {
	row := q.db.QueryRow(ctx, updateIntegration,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Credentials,
		arg.IsActive,
	)
	var i UpdateIntegrationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
