// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	Provider              string           `json:"provider"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           pgtype.Text      `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	IDToken               pgtype.Text      `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Agent struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Config      []byte             `json:"config"`
	Status      pgtype.Text        `json:"status"`
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Execution struct {
	ID              pgtype.UUID        `json:"id"`
	WorkflowID      pgtype.UUID        `json:"workflow_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	Status          pgtype.Text        `json:"status"`
	InputData       []byte             `json:"input_data"`
	OutputData      []byte             `json:"output_data"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ExecutionTimeMs pgtype.Int4        `json:"execution_time_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ExecutionStep struct {
	ID              pgtype.UUID        `json:"id"`
	ExecutionID     pgtype.UUID        `json:"execution_id"`
	StepName        string             `json:"step_name"`
	StepType        string             `json:"step_type"`
	Status          pgtype.Text        `json:"status"`
	InputData       []byte             `json:"input_data"`
	OutputData      []byte             `json:"output_data"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ExecutionTimeMs pgtype.Int4        `json:"execution_time_ms"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Integration struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Config      []byte             `json:"config"`
	Credentials []byte             `json:"credentials"`
	UserID      string             `json:"user_id"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	IpAddress pgtype.Text      `json:"ipAddress"`
	UserAgent pgtype.Text      `json:"userAgent"`
	UserId    string           `json:"userId"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"emailVerified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	LastLogin     pgtype.Timestamp `json:"last_login"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}

type Workflow struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Definition  []byte             `json:"definition"`
	Version     pgtype.Int4        `json:"version"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
