// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	Provider              string           `json:"provider"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           pgtype.Text      `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	IDToken               pgtype.Text      `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Agent struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Config      []byte             `json:"config"`
	Status      pgtype.Text        `json:"status"`
	UserID      string             `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AppConnection struct {
	ID          pgtype.UUID        `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Name        string             `json:"name"`
	AppName     string             `json:"app_name"`
	Config      []byte             `json:"config"`
	Credentials []byte             `json:"credentials"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FileStorage struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Filename  string             `json:"filename"`
	Size      int32              `json:"size"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Flow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	FolderID  pgtype.UUID        `json:"folder_id"`
	Status    pgtype.Text        `json:"status"`
	Schedule  []byte             `json:"schedule"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FlowRun struct {
	ID              pgtype.UUID        `json:"id"`
	FlowVersionID   pgtype.UUID        `json:"flow_version_id"`
	ProjectID       pgtype.UUID        `json:"project_id"`
	Status          pgtype.Text        `json:"status"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	FinishTime      pgtype.Timestamptz `json:"finish_time"`
	Environment     pgtype.Text        `json:"environment"`
	FlowDisplayName pgtype.Text        `json:"flow_display_name"`
	LogsFileID      pgtype.UUID        `json:"logs_file_id"`
	Tags            []string           `json:"tags"`
	PauseMetadata   []byte             `json:"pause_metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FlowVersion struct {
	ID          pgtype.UUID        `json:"id"`
	FlowID      pgtype.UUID        `json:"flow_id"`
	Version     int32              `json:"version"`
	DisplayName string             `json:"display_name"`
	Trigger     []byte             `json:"trigger"`
	Steps       []byte             `json:"steps"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Folder struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Integration struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Config      []byte             `json:"config"`
	Credentials []byte             `json:"credentials"`
	UserID      string             `json:"user_id"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID              pgtype.UUID        `json:"id"`
	DisplayName     string             `json:"display_name"`
	OwnerID         string             `json:"owner_id"`
	PlatformID      pgtype.UUID        `json:"platform_id"`
	NotifyStatus    pgtype.Text        `json:"notify_status"`
	ExternalID      pgtype.Text        `json:"external_id"`
	ReleasesEnabled pgtype.Bool        `json:"releases_enabled"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
	IpAddress pgtype.Text      `json:"ipAddress"`
	UserAgent pgtype.Text      `json:"userAgent"`
	UserId    string           `json:"userId"`
}

type StepRun struct {
	ID           pgtype.UUID        `json:"id"`
	FlowRunID    pgtype.UUID        `json:"flow_run_id"`
	StepName     string             `json:"step_name"`
	Status       pgtype.Text        `json:"status"`
	Input        []byte             `json:"input"`
	Output       []byte             `json:"output"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Duration     pgtype.Int4        `json:"duration"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	FinishTime   pgtype.Timestamptz `json:"finish_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type TriggerEvent struct {
	ID        pgtype.UUID        `json:"id"`
	FlowID    pgtype.UUID        `json:"flow_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	SourceID  pgtype.Text        `json:"source_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"emailVerified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
	LastLogin     pgtype.Timestamp `json:"last_login"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expiresAt"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}
