// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (display_name, owner_id, platform_id, notify_status, external_id, releases_enabled, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, display_name, owner_id, platform_id, notify_status, external_id, releases_enabled, metadata, created_at, updated_at
`

type CreateProjectParams struct {
	DisplayName     string      `json:"display_name"`
	OwnerID         string      `json:"owner_id"`
	PlatformID      pgtype.UUID `json:"platform_id"`
	NotifyStatus    pgtype.Text `json:"notify_status"`
	ExternalID      pgtype.Text `json:"external_id"`
	ReleasesEnabled pgtype.Bool `json:"releases_enabled"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.DisplayName,
		arg.OwnerID,
		arg.PlatformID,
		arg.NotifyStatus,
		arg.ExternalID,
		arg.ReleasesEnabled,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.OwnerID,
		&i.PlatformID,
		&i.NotifyStatus,
		&i.ExternalID,
		&i.ReleasesEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, display_name, owner_id, platform_id, notify_status, external_id, releases_enabled, metadata, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.OwnerID,
		&i.PlatformID,
		&i.NotifyStatus,
		&i.ExternalID,
		&i.ReleasesEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectUsage = `-- name: GetProjectUsage :one
SELECT 
    p.id,
    p.display_name,
    COUNT(DISTINCT f.id) as flow_count,
    COUNT(DISTINCT fr.id) as flow_run_count,
    COUNT(DISTINCT ac.id) as connection_count
FROM projects p
LEFT JOIN flows f ON f.project_id = p.id
LEFT JOIN flow_runs fr ON fr.project_id = p.id AND fr.created_at >= NOW() - INTERVAL '30 days'
LEFT JOIN app_connections ac ON ac.project_id = p.id
WHERE p.id = $1
GROUP BY p.id, p.display_name
`

type GetProjectUsageRow struct {
	ID              pgtype.UUID `json:"id"`
	DisplayName     string      `json:"display_name"`
	FlowCount       int64       `json:"flow_count"`
	FlowRunCount    int64       `json:"flow_run_count"`
	ConnectionCount int64       `json:"connection_count"`
}

func (q *Queries) GetProjectUsage(ctx context.Context, id pgtype.UUID) (GetProjectUsageRow, error) {
	row := q.db.QueryRow(ctx, getProjectUsage, id)
	var i GetProjectUsageRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.FlowCount,
		&i.FlowRunCount,
		&i.ConnectionCount,
	)
	return i, err
}

const getProjectsByOwnerID = `-- name: GetProjectsByOwnerID :many

SELECT id, display_name, owner_id, platform_id, notify_status, external_id, releases_enabled, metadata, created_at, updated_at
FROM projects
WHERE owner_id = $1
ORDER BY created_at DESC
`

// Projects queries
func (q *Queries) GetProjectsByOwnerID(ctx context.Context, ownerID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.OwnerID,
			&i.PlatformID,
			&i.NotifyStatus,
			&i.ExternalID,
			&i.ReleasesEnabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET display_name = $2, notify_status = $3, external_id = $4, releases_enabled = $5, metadata = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, display_name, owner_id, platform_id, notify_status, external_id, releases_enabled, metadata, created_at, updated_at
`

type UpdateProjectParams struct {
	ID              pgtype.UUID `json:"id"`
	DisplayName     string      `json:"display_name"`
	NotifyStatus    pgtype.Text `json:"notify_status"`
	ExternalID      pgtype.Text `json:"external_id"`
	ReleasesEnabled pgtype.Bool `json:"releases_enabled"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.DisplayName,
		arg.NotifyStatus,
		arg.ExternalID,
		arg.ReleasesEnabled,
		arg.Metadata,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.OwnerID,
		&i.PlatformID,
		&i.NotifyStatus,
		&i.ExternalID,
		&i.ReleasesEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
