// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (CreateIntegrationRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteAgent(ctx context.Context, id pgtype.UUID) error
	DeleteIntegration(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, token string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteWorkflow(ctx context.Context, id pgtype.UUID) error
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountByUserID(ctx context.Context, userID string) (Account, error)
	GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error)
	GetAgentIDByWorkflowID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetAgentsByUserID(ctx context.Context, userID string) ([]Agent, error)
	GetExecutionByID(ctx context.Context, id pgtype.UUID) (Execution, error)
	GetExecutionsByAgentID(ctx context.Context, arg GetExecutionsByAgentIDParams) ([]Execution, error)
	GetExecutionsByUserID(ctx context.Context, arg GetExecutionsByUserIDParams) ([]Execution, error)
	GetExecutionsByWorkflowID(ctx context.Context, arg GetExecutionsByWorkflowIDParams) ([]Execution, error)
	GetIntegrationByID(ctx context.Context, id pgtype.UUID) (Integration, error)
	GetIntegrationsByUserID(ctx context.Context, userID string) ([]GetIntegrationsByUserIDRow, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSessionByToken(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error)
	GetWorkflowsByAgentID(ctx context.Context, agentID pgtype.UUID) ([]Workflow, error)
	GetWorkflowsByUserID(ctx context.Context, userID string) ([]Workflow, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error)
	UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (UpdateIntegrationRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
