// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: step_runs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStepRun = `-- name: CreateStepRun :one
INSERT INTO step_runs (
    flow_run_id,
    step_name,
    status,
    input,
    start_time
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at
`

type CreateStepRunParams struct {
	FlowRunID pgtype.UUID        `json:"flow_run_id"`
	StepName  string             `json:"step_name"`
	Status    pgtype.Text        `json:"status"`
	Input     []byte             `json:"input"`
	StartTime pgtype.Timestamptz `json:"start_time"`
}

func (q *Queries) CreateStepRun(ctx context.Context, arg CreateStepRunParams) (StepRun, error) {
	row := q.db.QueryRow(ctx, createStepRun,
		arg.FlowRunID,
		arg.StepName,
		arg.Status,
		arg.Input,
		arg.StartTime,
	)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStepRunsByFlowRunID = `-- name: DeleteStepRunsByFlowRunID :exec
DELETE FROM step_runs 
WHERE flow_run_id = $1
`

func (q *Queries) DeleteStepRunsByFlowRunID(ctx context.Context, flowRunID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStepRunsByFlowRunID, flowRunID)
	return err
}

const getRunningStepRuns = `-- name: GetRunningStepRuns :many
SELECT sr.id, sr.flow_run_id, sr.step_name, sr.status, sr.input, sr.output, sr.error_message, sr.duration, sr.start_time, sr.finish_time, sr.created_at, sr.updated_at, fr.project_id 
FROM step_runs sr
JOIN flow_runs fr ON fr.id = sr.flow_run_id
WHERE sr.status = 'RUNNING'
ORDER BY sr.start_time ASC
`

type GetRunningStepRunsRow struct {
	ID           pgtype.UUID        `json:"id"`
	FlowRunID    pgtype.UUID        `json:"flow_run_id"`
	StepName     string             `json:"step_name"`
	Status       pgtype.Text        `json:"status"`
	Input        []byte             `json:"input"`
	Output       []byte             `json:"output"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Duration     pgtype.Int4        `json:"duration"`
	StartTime    pgtype.Timestamptz `json:"start_time"`
	FinishTime   pgtype.Timestamptz `json:"finish_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ProjectID    pgtype.UUID        `json:"project_id"`
}

func (q *Queries) GetRunningStepRuns(ctx context.Context) ([]GetRunningStepRunsRow, error) {
	rows, err := q.db.Query(ctx, getRunningStepRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRunningStepRunsRow{}
	for rows.Next() {
		var i GetRunningStepRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowRunID,
			&i.StepName,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.Duration,
			&i.StartTime,
			&i.FinishTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStepRunByFlowRunAndName = `-- name: GetStepRunByFlowRunAndName :one
SELECT id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at FROM step_runs 
WHERE flow_run_id = $1 AND step_name = $2
`

type GetStepRunByFlowRunAndNameParams struct {
	FlowRunID pgtype.UUID `json:"flow_run_id"`
	StepName  string      `json:"step_name"`
}

func (q *Queries) GetStepRunByFlowRunAndName(ctx context.Context, arg GetStepRunByFlowRunAndNameParams) (StepRun, error) {
	row := q.db.QueryRow(ctx, getStepRunByFlowRunAndName, arg.FlowRunID, arg.StepName)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStepRunByID = `-- name: GetStepRunByID :one
SELECT id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at FROM step_runs 
WHERE id = $1
`

func (q *Queries) GetStepRunByID(ctx context.Context, id pgtype.UUID) (StepRun, error) {
	row := q.db.QueryRow(ctx, getStepRunByID, id)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStepRunStats = `-- name: GetStepRunStats :one
SELECT 
    COUNT(*) as total_steps,
    COUNT(CASE WHEN status = 'SUCCEEDED' THEN 1 END) as succeeded_steps,
    COUNT(CASE WHEN status = 'FAILED' THEN 1 END) as failed_steps,
    COUNT(CASE WHEN status = 'RUNNING' THEN 1 END) as running_steps,
    COUNT(CASE WHEN status = 'PAUSED' THEN 1 END) as paused_steps,
    COUNT(CASE WHEN status = 'SKIPPED' THEN 1 END) as skipped_steps,
    AVG(duration) as avg_duration_ms
FROM step_runs 
WHERE flow_run_id = $1
`

type GetStepRunStatsRow struct {
	TotalSteps     int64   `json:"total_steps"`
	SucceededSteps int64   `json:"succeeded_steps"`
	FailedSteps    int64   `json:"failed_steps"`
	RunningSteps   int64   `json:"running_steps"`
	PausedSteps    int64   `json:"paused_steps"`
	SkippedSteps   int64   `json:"skipped_steps"`
	AvgDurationMs  float64 `json:"avg_duration_ms"`
}

func (q *Queries) GetStepRunStats(ctx context.Context, flowRunID pgtype.UUID) (GetStepRunStatsRow, error) {
	row := q.db.QueryRow(ctx, getStepRunStats, flowRunID)
	var i GetStepRunStatsRow
	err := row.Scan(
		&i.TotalSteps,
		&i.SucceededSteps,
		&i.FailedSteps,
		&i.RunningSteps,
		&i.PausedSteps,
		&i.SkippedSteps,
		&i.AvgDurationMs,
	)
	return i, err
}

const getStepRunsByFlowRunID = `-- name: GetStepRunsByFlowRunID :many
SELECT id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at FROM step_runs 
WHERE flow_run_id = $1 
ORDER BY created_at ASC
`

func (q *Queries) GetStepRunsByFlowRunID(ctx context.Context, flowRunID pgtype.UUID) ([]StepRun, error) {
	rows, err := q.db.Query(ctx, getStepRunsByFlowRunID, flowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StepRun{}
	for rows.Next() {
		var i StepRun
		if err := rows.Scan(
			&i.ID,
			&i.FlowRunID,
			&i.StepName,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.ErrorMessage,
			&i.Duration,
			&i.StartTime,
			&i.FinishTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStepRunError = `-- name: UpdateStepRunError :one
UPDATE step_runs 
SET 
    error_message = $2,
    status = 'FAILED',
    finish_time = NOW(),
    duration = EXTRACT(EPOCH FROM (NOW() - start_time)) * 1000,
    updated_at = NOW()
WHERE id = $1 
RETURNING id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at
`

type UpdateStepRunErrorParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateStepRunError(ctx context.Context, arg UpdateStepRunErrorParams) (StepRun, error) {
	row := q.db.QueryRow(ctx, updateStepRunError, arg.ID, arg.ErrorMessage)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStepRunOutput = `-- name: UpdateStepRunOutput :one
UPDATE step_runs 
SET 
    output = $2,
    status = $3,
    finish_time = NOW(),
    duration = EXTRACT(EPOCH FROM (NOW() - start_time)) * 1000,
    updated_at = NOW()
WHERE id = $1 
RETURNING id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at
`

type UpdateStepRunOutputParams struct {
	ID     pgtype.UUID `json:"id"`
	Output []byte      `json:"output"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStepRunOutput(ctx context.Context, arg UpdateStepRunOutputParams) (StepRun, error) {
	row := q.db.QueryRow(ctx, updateStepRunOutput, arg.ID, arg.Output, arg.Status)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStepRunStatus = `-- name: UpdateStepRunStatus :one
UPDATE step_runs 
SET 
    status = $2,
    finish_time = CASE WHEN $2::TEXT IN ('SUCCEEDED', 'FAILED', 'SKIPPED') THEN NOW() ELSE finish_time END,
    duration = CASE WHEN $2::TEXT IN ('SUCCEEDED', 'FAILED', 'SKIPPED') THEN EXTRACT(EPOCH FROM (NOW() - start_time)) * 1000 ELSE duration END,
    updated_at = NOW()
WHERE id = $1 
RETURNING id, flow_run_id, step_name, status, input, output, error_message, duration, start_time, finish_time, created_at, updated_at
`

type UpdateStepRunStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateStepRunStatus(ctx context.Context, arg UpdateStepRunStatusParams) (StepRun, error) {
	row := q.db.QueryRow(ctx, updateStepRunStatus, arg.ID, arg.Status)
	var i StepRun
	err := row.Scan(
		&i.ID,
		&i.FlowRunID,
		&i.StepName,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.ErrorMessage,
		&i.Duration,
		&i.StartTime,
		&i.FinishTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
