// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (agent_id, name, description, definition, version, is_active) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, agent_id, name, description, definition, version, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Definition  []byte      `json:"definition"`
	Version     pgtype.Int4 `json:"version"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.Version,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows 
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, agent_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE id = $1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowsByAgentID = `-- name: GetWorkflowsByAgentID :many
SELECT id, agent_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE agent_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetWorkflowsByAgentID(ctx context.Context, agentID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getWorkflowsByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowsByUserID = `-- name: GetWorkflowsByUserID :many
SELECT w.id, w.agent_id, w.name, w.description, w.definition, w.version, w.is_active, w.created_at, w.updated_at 
FROM workflows w 
JOIN agents a ON w.agent_id = a.id 
WHERE a.user_id = $1 
ORDER BY w.created_at DESC
`

func (q *Queries) GetWorkflowsByUserID(ctx context.Context, userID string) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getWorkflowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows 
SET name = $2, description = $3, definition = $4, is_active = $5, updated_at = NOW() 
WHERE id = $1 
RETURNING id, agent_id, name, description, definition, version, is_active, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Definition  []byte      `json:"definition"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
