// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateWorkflowVersion = `-- name: ActivateWorkflowVersion :exec
UPDATE workflows 
SET is_active = true 
WHERE name = $1 AND user_id = $2 AND version = $3
`

type ActivateWorkflowVersionParams struct {
	Name    string      `json:"name"`
	UserID  string      `json:"user_id"`
	Version pgtype.Int4 `json:"version"`
}

func (q *Queries) ActivateWorkflowVersion(ctx context.Context, arg ActivateWorkflowVersionParams) error {
	_, err := q.db.Exec(ctx, activateWorkflowVersion, arg.Name, arg.UserID, arg.Version)
	return err
}

const associateAgentWithWorkflow = `-- name: AssociateAgentWithWorkflow :one
INSERT INTO agent_workflows (agent_id, workflow_id, is_primary) 
VALUES ($1, $2, $3) 
RETURNING id, agent_id, workflow_id, is_primary, created_at
`

type AssociateAgentWithWorkflowParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
	IsPrimary  pgtype.Bool `json:"is_primary"`
}

// Agent-Workflow Association queries
func (q *Queries) AssociateAgentWithWorkflow(ctx context.Context, arg AssociateAgentWithWorkflowParams) (AgentWorkflow, error) {
	row := q.db.QueryRow(ctx, associateAgentWithWorkflow, arg.AgentID, arg.WorkflowID, arg.IsPrimary)
	var i AgentWorkflow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.WorkflowID,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (user_id, name, description, definition, version, is_active) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, user_id, name, description, definition, version, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	UserID      string      `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Definition  []byte      `json:"definition"`
	Version     pgtype.Int4 `json:"version"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.Version,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowVersion = `-- name: CreateWorkflowVersion :one
INSERT INTO workflows (user_id, name, description, definition, version, is_active) 
VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, user_id, name, description, definition, version, is_active, created_at, updated_at
`

type CreateWorkflowVersionParams struct {
	UserID      string      `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Definition  []byte      `json:"definition"`
	Version     pgtype.Int4 `json:"version"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateWorkflowVersion(ctx context.Context, arg CreateWorkflowVersionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflowVersion,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.Version,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWorkflowVersions = `-- name: DeactivateWorkflowVersions :exec
UPDATE workflows 
SET is_active = false 
WHERE name = $1 AND user_id = $2
`

type DeactivateWorkflowVersionsParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeactivateWorkflowVersions(ctx context.Context, arg DeactivateWorkflowVersionsParams) error {
	_, err := q.db.Exec(ctx, deactivateWorkflowVersions, arg.Name, arg.UserID)
	return err
}

const deleteAllWorkflowVersions = `-- name: DeleteAllWorkflowVersions :exec
DELETE FROM workflows 
WHERE name = $1 AND user_id = $2
`

type DeleteAllWorkflowVersionsParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAllWorkflowVersions(ctx context.Context, arg DeleteAllWorkflowVersionsParams) error {
	_, err := q.db.Exec(ctx, deleteAllWorkflowVersions, arg.Name, arg.UserID)
	return err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows 
WHERE id = $1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, id)
	return err
}

const getAgentWorkflowAssociations = `-- name: GetAgentWorkflowAssociations :many
SELECT id, agent_id, workflow_id, is_primary, created_at 
FROM agent_workflows 
WHERE agent_id = $1
`

func (q *Queries) GetAgentWorkflowAssociations(ctx context.Context, agentID pgtype.UUID) ([]AgentWorkflow, error) {
	rows, err := q.db.Query(ctx, getAgentWorkflowAssociations, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentWorkflow{}
	for rows.Next() {
		var i AgentWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.WorkflowID,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestWorkflowVersionByName = `-- name: GetLatestWorkflowVersionByName :one
SELECT id, user_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE name = $1 AND user_id = $2 
ORDER BY version DESC 
LIMIT 1
`

type GetLatestWorkflowVersionByNameParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetLatestWorkflowVersionByName(ctx context.Context, arg GetLatestWorkflowVersionByNameParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getLatestWorkflowVersionByName, arg.Name, arg.UserID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, user_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE id = $1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id pgtype.UUID) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowVersion = `-- name: GetWorkflowVersion :one
SELECT id, user_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE name = $1 AND user_id = $2 AND version = $3
`

type GetWorkflowVersionParams struct {
	Name    string      `json:"name"`
	UserID  string      `json:"user_id"`
	Version pgtype.Int4 `json:"version"`
}

func (q *Queries) GetWorkflowVersion(ctx context.Context, arg GetWorkflowVersionParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowVersion, arg.Name, arg.UserID, arg.Version)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowVersionHistory = `-- name: GetWorkflowVersionHistory :many
SELECT id, user_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE name = $1 AND user_id = $2 
ORDER BY version DESC
`

type GetWorkflowVersionHistoryParams struct {
	Name   string `json:"name"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetWorkflowVersionHistory(ctx context.Context, arg GetWorkflowVersionHistoryParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getWorkflowVersionHistory, arg.Name, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowsByAgentID = `-- name: GetWorkflowsByAgentID :many
SELECT w.id, w.user_id, w.name, w.description, w.definition, w.version, w.is_active, w.created_at, w.updated_at 
FROM workflows w 
JOIN agent_workflows aw ON w.id = aw.workflow_id 
WHERE aw.agent_id = $1 
ORDER BY w.created_at DESC
`

func (q *Queries) GetWorkflowsByAgentID(ctx context.Context, agentID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getWorkflowsByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowsByUserID = `-- name: GetWorkflowsByUserID :many
SELECT id, user_id, name, description, definition, version, is_active, created_at, updated_at 
FROM workflows 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetWorkflowsByUserID(ctx context.Context, userID string) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, getWorkflowsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentWorkflowAssociation = `-- name: RemoveAgentWorkflowAssociation :exec
DELETE FROM agent_workflows 
WHERE agent_id = $1 AND workflow_id = $2
`

type RemoveAgentWorkflowAssociationParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) RemoveAgentWorkflowAssociation(ctx context.Context, arg RemoveAgentWorkflowAssociationParams) error {
	_, err := q.db.Exec(ctx, removeAgentWorkflowAssociation, arg.AgentID, arg.WorkflowID)
	return err
}

const setPrimaryWorkflowForAgent = `-- name: SetPrimaryWorkflowForAgent :exec
UPDATE agent_workflows 
SET is_primary = CASE WHEN workflow_id = $2 THEN true ELSE false END 
WHERE agent_id = $1
`

type SetPrimaryWorkflowForAgentParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	WorkflowID pgtype.UUID `json:"workflow_id"`
}

func (q *Queries) SetPrimaryWorkflowForAgent(ctx context.Context, arg SetPrimaryWorkflowForAgentParams) error {
	_, err := q.db.Exec(ctx, setPrimaryWorkflowForAgent, arg.AgentID, arg.WorkflowID)
	return err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows 
SET name = $2, description = $3, definition = $4, is_active = $5, updated_at = NOW() 
WHERE id = $1 
RETURNING id, user_id, name, description, definition, version, is_active, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Definition  []byte      `json:"definition"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.IsActive,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
